apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
  labels:
    app: booking-service
spec:
  selector:
    matchLabels:
      app: booking-service
  replicas: 3
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
      - name: booking-service
        image: lhr.ocir.io/lrvoxmufvusf/vs-repo/vs-booking-service:1.0
        imagePullPolicy: Always
        ports:
        - name: booking-service
          containerPort: 8080
          protocol: TCP
      imagePullSecrets:
        - name: vs-oke-secret2
---
apiVersion: v1
kind: Service
metadata:
  name: booking-service-svc
spec:
  selector:
    app: booking-service
  ports:
    - port: 8081
      targetPort: 8080
  type:  ClusterIP
