apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-service
  labels:
    app: hotel-service
spec:
  selector:
    matchLabels: 
      app: hotel-service 
  replicas: 3
  template:
    metadata:
      labels:
        app: hotel-service
    spec:
      containers:
      - name: hotel-service
        image: lhr.ocir.io/lrvoxmufvusf/vs-repo/vs-hotel-service:1.0
        imagePullPolicy: Always
        ports:
        - name: hotel-service
          containerPort: 8081
          protocol: TCP
      imagePullSecrets:
        - name: vs-oke-secret
---
apiVersion: v1
kind: Service
metadata:
  name: hotel-service-svc
spec:
  selector:
    app: hotel-service
  ports:
    - port: 80
      targetPort: 8081
  type: ClusterIP
      
