apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/app-root: /app1
  name: approot
  namespace: 
spec:
  ingressClassName: nginx
  rules:
  - host: approot.bar.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hotel-service-svc
            port: 
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: customer-service-svc
            port: 
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: booking-service-svc
            port: 
              number: 80
      
